name: CI
on: 
  pull_request:
    paths:
      - 'application/src/main/resources/thingsboard.yml'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.2

      - name: Run Verification Script
        run: tools/src/main/python/check_env_variables.py
